#!/bin/sh

echo 'Running git pre-commit tests'

# Run ESLint against any staged (added, copied or modified) files with names
# ending in ".js". If there are any ESLint errors the commit will be aborted.
JS_FILES="$(git diff --cached --name-only --diff-filter=ACM | grep '.js$')"
if [ ! -z "$JS_FILES" ]; then
  echo $JS_FILES | xargs npm run lint || { exit 1; }
else
  echo 'No staged JavaScript files... skipping ESLint'
fi
