#!/bin/sh

echo 'Running git pre-push tests'

# Run ESLint against any staged (added, copied or modified) files with names
# ending in ".js". If there are any ESLint errors the push will be aborted.
JS_FILES="$(git diff --cached --name-only --diff-filter=ACM origin/master | grep '.js$')"
if [ ! -z "$JS_FILES" ]; then
  echo $JS_FILES | xargs npm run lint || { exit 1; }
else
  echo 'No staged JavaScript files... skipping ESLint'
fi

# Run unit tests. If there are any failures the push will be aborted.
CI=true npm t
exit $?
